$ErrorActionPreference='Stop'
. (Join-Path (Get-Location).Path 'src/dependencies/DependencyEngine.ps1')
function Assert($Condition,$Message){ if(-not $Condition){ throw $Message } }
$tmp=Join-Path (Get-Location).Path 'tests/fixtures/dependency-file.txt'; 'ok'|Set-Content $tmp
$dir=Join-Path (Get-Location).Path 'tests/fixtures'
$fileDep=New-UndiesDependencyRecord -DependencyId 'D-FILE' -Type 'FILE' -ExactName $tmp -ReasonRequired 'file required' -ExpectedFormat 'existing file path' -ManualAction 'Create the file' -PowerShellAction "New-Item -ItemType File -Path '$tmp'" -ValidationCommand "Test-Path '$tmp'" -SuccessCondition 'True' -ResumeModule 'UND-007' -ResumeCheckpoint 'file-ready'; Assert (Test-UndiesDependency $fileDep) 'file dependency failed'
$dirDep=New-UndiesDependencyRecord -DependencyId 'D-DIR' -Type 'DIRECTORY' -ExactName $dir -ReasonRequired 'directory required' -ExpectedFormat 'existing directory path' -ManualAction 'Create directory' -PowerShellAction "New-Item -ItemType Directory -Path '$dir'" -ValidationCommand "Test-Path '$dir' -PathType Container" -SuccessCondition 'True' -ResumeModule 'UND-007' -ResumeCheckpoint 'dir-ready'; Assert (Test-UndiesDependency $dirDep) 'directory dependency failed'
$urlDep=New-UndiesDependencyRecord -DependencyId 'D-URL' -Type 'REPOSITORY_URL' -ExactName 'https://github.com/ENDLESSOG81/UNDIES.git' -ReasonRequired 'repo url required' -ExpectedFormat 'https URL' -ManualAction 'Provide URL' -PowerShellAction '$RepositoryUrl = Read-Host "Repository URL"' -ValidationCommand '[Uri]::IsWellFormedUriString($RepositoryUrl,[UriKind]::Absolute)' -SuccessCondition 'True' -ResumeModule 'UND-007' -ResumeCheckpoint 'url-ready'; Assert (Test-UndiesDependency $urlDep) 'url dependency failed'
[Environment]::SetEnvironmentVariable('UNDIES_TEST_ENV','present','Process')
$envDep=New-UndiesDependencyRecord -DependencyId 'D-ENV' -Type 'ENVIRONMENT_VARIABLE' -ExactName 'UNDIES_TEST_ENV' -ReasonRequired 'env required' -ExpectedFormat 'non-empty value' -ManualAction 'Set env var' -PowerShellAction '$env:UNDIES_TEST_ENV="value"' -ValidationCommand 'Test-Path Env:UNDIES_TEST_ENV' -SuccessCondition 'True' -ResumeModule 'UND-007' -ResumeCheckpoint 'env-ready'; Assert (Test-UndiesDependency $envDep) 'env dependency failed'
$appDep=New-UndiesDependencyRecord -DependencyId 'D-APP' -Type 'APPLICATION' -ExactName 'git' -ReasonRequired 'application required' -ExpectedFormat 'command name' -ManualAction 'Install or expose application' -PowerShellAction 'Get-Command git' -ValidationCommand 'Get-Command git' -SuccessCondition 'Command exists' -ResumeModule 'UND-007' -ResumeCheckpoint 'app-ready'; Assert (Test-UndiesDependency $appDep) 'application dependency failed'
$authDep=New-UndiesDependencyRecord -DependencyId 'D-AUTH' -Type 'ACCOUNT_AUTHORIZATION' -ExactName 'GitHub authorization' -ReasonRequired 'authorization required' -ExpectedFormat 'authenticated account, no token in output' -Sensitive:$true -ManualAction 'Authenticate locally' -PowerShellAction 'Read-Host "Press Enter after authorization"' -ValidationCommand 'git ls-remote origin' -SuccessCondition 'Remote responds' -ResumeModule 'UND-007' -ResumeCheckpoint 'auth-ready'; $txt=Format-UndiesManualAction -Module ([pscustomobject]@{module_id='UND-007';module_name='Dependency'}) -Dependency $authDep; Assert ($txt -match 'MANUAL ACTION REQUIRED' -and $txt -match 'Sensitive value' -and $txt -notmatch 'token=') 'manual action unsafe'
$missingFailed=$false; try{ New-UndiesDependencyRecord -DependencyId '' -Type 'FILE' -ExactName '' -ReasonRequired '' -ExpectedFormat '' -ManualAction '' -PowerShellAction '' -ValidationCommand '' -SuccessCondition '' -ResumeModule '' -ResumeCheckpoint ''|Out-Null }catch{$missingFailed=$true}; Assert $missingFailed 'blank dependency accepted'
'UND-007_TEST passed=7 failed=0 skipped=0'
