param([switch]$Quiet)
$ErrorActionPreference='Stop'
$Root = Split-Path -Parent $PSScriptRoot
. (Join-Path $Root 'src/bootstrap/Core.ps1')
. (Join-Path $Root 'src/session/SessionEngine.ps1')
. (Join-Path $Root 'src/modules/ModuleQueue.ps1')
. (Join-Path $Root 'src/gates/GateEngine.ps1')
. (Join-Path $Root 'src/dependencies/DependencyEngine.ps1')
. (Join-Path $Root 'src/evidence/EvidenceEngine.ps1')
. (Join-Path $Root 'src/reporting/ReportEngine.ps1')
. (Join-Path $Root 'src/recovery/RecoveryEngine.ps1')
$script:Passed=0; $script:Failed=0; $script:Skipped=0; $script:Results=@()
function Add-Result($Name,$Status,$Message=''){ if($Status -eq 'PASS'){$script:Passed++}elseif($Status -eq 'SKIP'){$script:Skipped++}else{$script:Failed++}; $script:Results += [pscustomobject]@{name=$Name;status=$Status;message=$Message}; if(-not $Quiet){Write-Host ("[{0}] {1} {2}" -f $Status,$Name,$Message)} }
function It($Name,[scriptblock]$Body){ try{ & $Body; Add-Result $Name 'PASS' }catch{ Add-Result $Name 'FAIL' $_.Exception.Message } }
function Assert($Condition,$Message){ if(-not $Condition){ throw $Message } }
function New-TestBlueDependency {
    New-UndiesDependencyRecord -DependencyId 'BLUE-TEST' -Type 'OPERATOR_INPUT' -ExactName 'Operator confirmation' -ReasonRequired 'Exact operator input required' -ExpectedFormat 'non-secret confirmation' -Sensitive:$false -SourceOrOwner 'Human operator' -ManualAction 'Provide confirmation' -PowerShellAction '$value = Read-Host "Confirmation"' -ValidationCommand 'Test-Path .' -SuccessCondition 'True' -FailureCondition 'Remain BLUE' -ResumeModule 'UND-011' -ResumeCheckpoint 'blue-checkpoint'
}
$RunRoot=Join-Path $env:TEMP ('undies-tests-'+[guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $RunRoot | Out-Null
try {
It '01 clean initialization' { $m=Initialize-UndiesProject -Root $RunRoot; Assert ($m.project_code -eq 'UND') 'manifest missing project code' }
It '02 repeated initialization' { $a=Initialize-UndiesProject -Root $RunRoot; $b=Initialize-UndiesProject -Root $RunRoot; Assert ($a.created_date -eq $b.created_date) 'manifest rewritten' }
It '03 existing-file preservation' { $p=Join-Path $RunRoot 'user.txt'; 'keep'|Set-Content $p; Initialize-UndiesProject -Root $RunRoot|Out-Null; Assert ((Get-Content $p -Raw).Trim() -eq 'keep') 'user file changed' }
It '04 session creation' { $s=New-UndiesSession -Root $RunRoot -PendingModules @('UND-001'); Assert ($s.session_id -match '^UND-UND-\d{8}-\d{3}$') 'bad session ID' }
It '05 session closure' { $s=Get-UndiesInterruptedSession -Root $RunRoot; $c=Close-UndiesSession -Root $RunRoot -SessionId $s.session_id; Assert ($c.final_status -eq 'COMPLETE') 'not closed' }
It '06 interrupted-session recovery' { $s=New-UndiesSession -Root $RunRoot -PendingModules @('UND-001'); $r=Resume-UndiesSession -Root $RunRoot; Assert ($r.session_id -eq $s.session_id) 'resume mismatch'; Close-UndiesSession -Root $RunRoot -SessionId $s.session_id|Out-Null }
It '07 single-module queue' { $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='UND-001';dependencies=@()}); $q=Start-UndiesNextModule $q; Assert ($q.active.module_id -eq 'UND-001') 'single queue failed' }
It '08 ten-module queue' { $mods=1..10|ForEach-Object{[pscustomobject]@{module_id=('UND-{0:000}' -f $_);dependencies=@()}}; $q=New-UndiesModuleQueue $mods; Assert ($q.pending.Count -eq 10) 'ten queue failed' }
It '09 duplicate module rejection' { $failed=$false; try{New-UndiesModuleQueue @([pscustomobject]@{module_id='X';dependencies=@()},[pscustomobject]@{module_id='X';dependencies=@()})|Out-Null}catch{$failed=$true}; Assert $failed 'duplicate accepted' }
It '10 invalid module rejection' { $r=Test-UndiesContracts -Root $Root -ModuleFiles @((Join-Path $Root 'tests/fixtures/invalid-module-status.json')); Assert (-not $r.Passed) 'invalid module accepted' }
It '11 GREEN continuation' { $d=New-UndiesGateDecision -ModuleId 'UND-006' -Status 'GREEN' -Reason 'passed'; Assert ($d.continuation_decision -eq 'advance') 'GREEN failed' }
It '12 non-blocking YELLOW continuation' { $d=New-UndiesGateDecision -ModuleId 'UND-006' -Status 'YELLOW' -Reason 'warning' -BlocksNextModule:$false; Assert ($d.continuation_decision -eq 'advance') 'YELLOW failed' }
It '13 blocking YELLOW stop' { $d=New-UndiesGateDecision -ModuleId 'UND-006' -Status 'YELLOW' -Reason 'warning' -BlocksNextModule:$true; Assert ($d.continuation_decision -eq 'stop') 'blocking YELLOW failed' }
It '14 RED stop' { $d=New-UndiesGateDecision -ModuleId 'UND-006' -Status 'RED' -Reason 'failed'; Assert ($d.continuation_decision -eq 'stop') 'RED failed' }
It '15 BLOCKED preflight' { $d=New-UndiesGateDecision -ModuleId 'UND-006' -Status 'BLOCKED' -Reason 'blocked'; Assert ($d.continuation_decision -eq 'stop') 'BLOCKED failed' }
It '16 exact dependency reporting' { $dep=New-UndiesDependencyRecord -DependencyId 'D' -Type 'FILE' -ExactName 'C:\x' -ReasonRequired 'needed' -ExpectedFormat 'path' -ManualAction 'create' -PowerShellAction 'New-Item C:\x' -ValidationCommand 'Test-Path C:\x' -SuccessCondition 'True' -ResumeModule 'UND-007' -ResumeCheckpoint 'ready'; $txt=Format-UndiesManualAction -Module ([pscustomobject]@{module_id='UND-007';module_name='Dependency'}) -Dependency $dep; Assert ($txt -match 'VALIDATION COMMAND' -and $txt -match 'RESUME POINT') 'manual action incomplete' }
It '17 sensitive-value redaction' { $red=Protect-UndiesText 'Authorization: Bearer abcdef token=secret'; Assert ($red -notmatch 'abcdef|secret') 'secret leaked' }
It '18 evidence creation' { $e=Add-UndiesEvidenceEvent -Root $RunRoot -SessionId 'S' -ModuleId 'UND-008' -EventType 'test' -Action 'evidence' -Details @{token='secret'}; $p=Get-UndiesEvidencePath -Root $RunRoot -SessionId 'S'; Assert ((Test-Path $p) -and ((Get-Content $p -Raw) -notmatch 'secret')) 'evidence failed' }
It '19 module report generation' { $p=New-UndiesModuleReport -Root $RunRoot -Report @{SessionId='S';ModuleId='UND-009';ModuleName='Report';Objective='test';Status='GREEN';CommitHash='abc';PushResult='ok'}; Assert ((Get-Content $p -Raw) -match 'Commit hash: abc') 'module report failed' }
It '20 final session report generation' { $p=New-UndiesSessionReport -Root $RunRoot -SessionId 'S' -ModuleResults @([pscustomobject]@{module_id='UND-001';status='GREEN'}); Assert (Test-Path $p) 'session report failed' }
It '21 corrupt-state detection' { 'not json'|Set-Content (Join-Path $RunRoot '.undies/recovery/BAD.checkpoint.json'); $r=Test-UndiesRecoveryState -Root $RunRoot -SessionId 'BAD'; Assert ($r.status -eq 'RED') 'corrupt state accepted' }
It '22 workspace-boundary enforcement' { Assert (-not (Test-UndiesPathInsideRoot -Root $RunRoot -Path '..\outside.txt')) 'outside path allowed' }
It '23 OneDrive protection' { $blocked=$false; try{Assert-UndiesWorkspaceSafe -Root 'C:\Users\Example\OneDrive\UNDIES'|Out-Null}catch{$blocked=$true}; Assert $blocked 'OneDrive allowed' }
It '24 offline foundation operation' { $r=Test-UndiesContracts -Root $Root; Assert $r.Passed 'contracts failed' }
It '25 help command' { $out=& (Join-Path $Root 'UNDIES.ps1') help; Assert (($out -join ' ') -match 'UNDIES 0.3.0-alpha.1') 'help failed' }
It '26 doctor command' { $json=& (Join-Path $Root 'UNDIES.ps1') doctor | ConvertFrom-Json; Assert ($json.status -eq 'GREEN') 'doctor not GREEN' }
It '27 portable single-file initialization' { & (Join-Path $Root 'build/package-undies.ps1') | Out-Null; $Portable=Join-Path $env:TEMP ('undies-portable-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Force -Path $Portable|Out-Null; Copy-Item (Join-Path $Root 'dist/UNDIES.ps1') $Portable; $m=& (Join-Path $Portable 'UNDIES.ps1') initialize | ConvertFrom-Json; Assert ($m.version -eq '0.3.0-alpha.1' -and $m.status -eq 'GREEN' -and (Test-Path (Join-Path $Portable '.undies/project/project.json')) -and (Test-Path (Join-Path $Portable '.undies/core/0.3.0-alpha.1/UNDIES.core.ps1'))) 'portable init failed'; Remove-Item $Portable -Recurse -Force }
It '28 portable single-file session lifecycle' { $Portable=Join-Path $env:TEMP ('undies-portable-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Force -Path $Portable|Out-Null; Copy-Item (Join-Path $Root 'dist/UNDIES.ps1') $Portable; $s=& (Join-Path $Portable 'UNDIES.ps1') session-start | ConvertFrom-Json; $c=& (Join-Path $Portable 'UNDIES.ps1') session-close -SessionId $s.session_id | ConvertFrom-Json; Assert ($c.final_status -eq 'COMPLETE') 'portable session failed'; Remove-Item $Portable -Recurse -Force }
It '29 safe repeated portable initialization' { $Portable=Join-Path $env:TEMP ('undies-portable-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Force -Path $Portable|Out-Null; Copy-Item (Join-Path $Root 'dist/UNDIES.ps1') $Portable; $a=& (Join-Path $Portable 'UNDIES.ps1') initialize | ConvertFrom-Json; $projectBefore=Get-Content (Join-Path $Portable '.undies/project/project.json') -Raw | ConvertFrom-Json; $b=& (Join-Path $Portable 'UNDIES.ps1') initialize | ConvertFrom-Json; $projectAfter=Get-Content (Join-Path $Portable '.undies/project/project.json') -Raw | ConvertFrom-Json; Assert ($a.status -eq 'GREEN' -and $b.status -eq 'GREEN' -and $projectBefore.created_date -eq $projectAfter.created_date) 'portable init not idempotent'; Remove-Item $Portable -Recurse -Force }
It '30 Git metadata inspection without modification' { $Safe='D:/GITHUB/undies'; $before=git -c safe.directory=$Safe status --short; $null=git -c safe.directory=$Safe remote get-url origin; $null=git -c safe.directory=$Safe branch --show-current; $after=git -c safe.directory=$Safe status --short; Assert (($before -join "`n") -eq ($after -join "`n")) 'git inspection modified status' }
It '31 BLUE canonical gate status' { $dep=New-TestBlueDependency; $d=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'needs input' -DependencyRecord $dep; Assert ($d.status -eq 'BLUE' -and $d.canonical_status -eq 'BLUE') 'BLUE not accepted' }
It '32 legacy alias loads' { Assert (Test-UndiesKnownStatus 'WAITING_FOR_EXTERNAL_DEPENDENCY') 'legacy alias unknown' }
It '33 legacy alias normalizes to BLUE' { Assert ((ConvertTo-UndiesCanonicalStatus 'WAITING_FOR_EXTERNAL_DEPENDENCY') -eq 'BLUE') 'legacy did not normalize' }
It '34 new records write BLUE' { $dep=New-TestBlueDependency; $d=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'WAITING_FOR_EXTERNAL_DEPENDENCY' -Reason 'legacy source' -DependencyRecord $dep; Assert ($d.status -eq 'BLUE' -and $d.source_status -eq 'WAITING_FOR_EXTERNAL_DEPENDENCY') 'canonical/source mismatch' }
It '35 BLUE without dependency fails' { $failed=$false; try{New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'missing'|Out-Null}catch{$failed=$true}; Assert $failed 'BLUE without dependency accepted' }
It '36 BLUE without resume checkpoint fails' { $dep=New-TestBlueDependency; $dep.resume_checkpoint=''; $failed=$false; try{New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'bad' -DependencyRecord $dep|Out-Null}catch{$failed=$true}; Assert $failed 'BLUE without checkpoint accepted' }
It '37 BLUE blocks next module' { $dep=New-TestBlueDependency; $d=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; Assert ($d.blocks_next_module -eq $true) 'BLUE did not block' }
It '38 BLUE pauses queue' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='UND-011';dependencies=@()},[pscustomobject]@{module_id='UND-012';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; Assert ($q.active.status -eq 'BLUE' -and $q.blue.Count -eq 1) 'BLUE did not pause active module' }
It '39 BLUE does not start next module' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='UND-011';dependencies=@()},[pscustomobject]@{module_id='UND-012';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; $failed=$false; try{Start-UndiesNextModule $q|Out-Null}catch{$failed=$true}; Assert $failed 'next module started after BLUE' }
It '40 BLUE is not RED' { $dep=New-TestBlueDependency; $d=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; Assert ($d.status -ne 'RED' -and $d.continuation_decision -eq 'PAUSE') 'BLUE treated as RED' }
It '41 BLUE has separate report total' { $p=New-UndiesSessionReport -Root $RunRoot -SessionId 'BLUE' -ModuleResults @([pscustomobject]@{module_id='A';status='BLUE'},[pscustomobject]@{module_id='B';status='RED'}); $txt=Get-Content $p -Raw; Assert ($txt -match 'BLUE=1' -and $txt -match 'RED=1') 'BLUE total missing' }
It '42 BLUE preserves completed modules' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='A';dependencies=@()},[pscustomobject]@{module_id='B';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'GREEN'; $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; Assert ($q.completed[0].module_id -eq 'A') 'completed not preserved' }
It '43 BLUE preserves pending modules' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='A';dependencies=@()},[pscustomobject]@{module_id='B';dependencies=@()},[pscustomobject]@{module_id='C';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; Assert ($q.pending[0].module_id -eq 'B') 'pending not preserved' }
It '44 BLUE resume fails when validation fails' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='A';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; $failed=$false; try{Resume-UndiesModuleQueue $q -DependencyValidated:$false|Out-Null}catch{$failed=$true}; Assert $failed 'resume bypassed validation' }
It '45 BLUE resume succeeds when validation passes' { $dep=New-TestBlueDependency; $q=New-UndiesModuleQueue @([pscustomobject]@{module_id='A';dependencies=@()}); $q=Start-UndiesNextModule $q; $q=Complete-UndiesActiveModule $q 'BLUE' -DependencyRecord $dep; $q=Resume-UndiesModuleQueue $q -DependencyValidated:$true; Assert ($q.active.status -eq 'IN_PROGRESS') 'resume failed' }
It '46 BLUE resumes exact checkpoint' { $dep=New-TestBlueDependency; $dep.resume_checkpoint='checkpoint-46'; $d=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; Assert ($d.resume_checkpoint -eq 'checkpoint-46') 'checkpoint mismatch' }
It '47 sensitive BLUE dependencies redacted' { $txt=Protect-UndiesText 'token=supersecret Authorization: Bearer abc123'; Assert ($txt -notmatch 'supersecret|abc123') 'sensitive output leaked' }
It '48 BLUE manual action has PowerShell action' { $dep=New-TestBlueDependency; $txt=Format-UndiesManualAction -Module ([pscustomobject]@{module_id='UND-011';module_name='Blue'}) -Dependency $dep; Assert ($txt -match 'POWERSHELL ACTION') 'PowerShell action missing' }
It '49 BLUE manual action has validation command' { $dep=New-TestBlueDependency; $txt=Format-UndiesManualAction -Module ([pscustomobject]@{module_id='UND-011';module_name='Blue'}) -Dependency $dep; Assert ($txt -match 'VALIDATION COMMAND') 'validation command missing' }
It '50 BLUE distinct from BLOCKED' { $dep=New-TestBlueDependency; $blue=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; $blocked=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLOCKED' -Reason 'preflight'; Assert ($blue.status -ne $blocked.status) 'BLUE equals BLOCKED' }
It '51 BLUE distinct from YELLOW' { $dep=New-TestBlueDependency; $blue=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; $yellow=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'YELLOW' -Reason 'warning' -BlocksNextModule:$false; Assert ($blue.status -ne $yellow.status) 'BLUE equals YELLOW' }
It '52 BLUE distinct from RED' { $dep=New-TestBlueDependency; $blue=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'BLUE' -Reason 'pause' -DependencyRecord $dep; $red=New-UndiesGateDecision -ModuleId 'UND-011' -Status 'RED' -Reason 'fail'; Assert ($blue.status -ne $red.status) 'BLUE equals RED' }
It '53 unknown statuses fail closed' { $failed=$false; try{New-UndiesGateDecision -ModuleId 'UND-011' -Status 'MAGENTA' -Reason 'bad'|Out-Null}catch{$failed=$true}; Assert $failed 'unknown status accepted' }
It '54 historical reports remain readable' { $p=New-UndiesModuleReport -Root $RunRoot -Report @{SessionId='LEGACY';ModuleId='UND-LEGACY';ModuleName='Legacy';Objective='read';Status='BLUE';SourceStatus='WAITING_FOR_EXTERNAL_DEPENDENCY';RequiredItem='file';Sensitive='NO';ValidationCommand='Test-Path x'}; $txt=Get-Content $p -Raw; Assert ($txt -match 'Source status: WAITING_FOR_EXTERNAL_DEPENDENCY' -and $txt -match 'Canonical status: BLUE') 'legacy report unreadable' }
It '55 portable dist supports BLUE behavior' { & (Join-Path $Root 'build/package-undies.ps1') | Out-Null; $Portable=Join-Path $env:TEMP ('undies-blue-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Force -Path $Portable|Out-Null; Copy-Item (Join-Path $Root 'dist/UNDIES.ps1') $Portable; $help=& (Join-Path $Portable 'UNDIES.ps1') help; $blue=& (Join-Path $Portable 'UNDIES.ps1') blue-report; $resumeFailed=$false; try{& (Join-Path $Portable 'UNDIES.ps1') resume|Out-Null}catch{$resumeFailed=$true}; $resume=& (Join-Path $Portable 'UNDIES.ps1') resume -DependencyValidated | ConvertFrom-Json; Assert (($help -match 'BLUE') -and ($blue -match 'BLUE GATE') -and $resumeFailed -and $resume.status -eq 'RESUMED') 'portable BLUE failed'; Remove-Item $Portable -Recurse -Force }
foreach($script in @('UND-004.Tests.ps1','UND-005.Tests.ps1','UND-006.Tests.ps1','UND-007.Tests.ps1','UND-008.Tests.ps1','UND-009.Tests.ps1')){ & (Join-Path $Root "tests/foundation/$script") | Out-Null }
} finally { if(Test-Path $RunRoot){ Remove-Item -LiteralPath $RunRoot -Recurse -Force -ErrorAction SilentlyContinue } }
$summary=[pscustomobject]@{passed=$script:Passed;failed=$script:Failed;skipped=$script:Skipped;results=$script:Results}
$reportPath=Join-Path $Root '.undies/reports/foundation-test-results.json'; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $reportPath)|Out-Null; $summary|ConvertTo-Json -Depth 20|Set-Content $reportPath -Encoding UTF8
Write-Host ("TOTAL passed={0} failed={1} skipped={2}" -f $script:Passed,$script:Failed,$script:Skipped)
if($script:Failed -gt 0){ exit 1 }
exit 0






